### ISSUE TITLE
Target sepsification

### ISSUE THREAD

**Issue by BahtiyarB** [galkan/flashlight#1]
hedef belirleme kısmında  domain de verilebilmeli. örn:  
./fener.py -t www.google.com -s screen 
./fener.py -d www.google.com 
hedef olarak domain adını alır. bu domain adını tarar 
Örnek kullanım: 
fener.py -d www.google.com -s screen -p project1
Scanning www.google.com (10.20.30.40) for open web ports
Finished screenshot scan. Results saved in output/project1/screen/ folder

**Comment by galkan** [comment]
ok
