### ISSUE TITLE
config dosyasi default ayarları 

### ISSUE THREAD

**Issue by BahtiyarB** [galkan/flashlight#2]
ilk çalışma sırasında config dosyasında okuması gereken parametreleri defaultta  config/fener.cfg   dosyasindan okuyabilmeli. ayrica parametre ile  verilirse başka dosyadan okuyabilmeli . 
1. Config dosyasını default okuma 
   fener.py ilk acilirken default dizinde bulunan fener.cfg dosyasi olup olmadigina bakacak. Var ise parametreleri oradan okuyacak. Bu defaultta yapacak, özellikle -c paramtresi ile config dosyasi paramtresi verilmesine ihtiyaç olmayacak. 

Eger ekstradan -c config.cfg paramtresi verilir ise, o zaman default doyasi değil, verilen config dosyasindan paramtreleri okuyacak. 

Config dosyası default : [fener dizini]/config/fener.cfg 

Örnek config dosyasi: 
cat fener.cfg 
[main]
project=ornek-project
thread=4
logfile=fener-log.txt
passive-timeout=10  
verbose=true
interface=eth0 

[ports]
tcp = 21,22,23,25,80,443,445,3128,8080
udp = 53,161

[nse]
;scripts = http-brute, smtp-_,  ftp-brute, snmp-_
scripts = http-enum

[screen-ports]
screenports=80,443,8080,8443 

ornek kullanım: 
fener.py -t 192.168.10.20/24 -s active 
Reading config file fener.cfg
Starting active scan against 192.168.10.20/24
Starting verbose output. 
Project name: ornek-project 
Starting nmap ping scan 
Discovering live host ip list 
Starting nmap port scan 
Starting nmap service detection 
Starting nmap OS detection 
Finished active scan. Results saved in  output/ornek-project/nmap/ folder

fener.py -t 192.168.10.20/24 -s screen 
Reading config file fener.cfg
Starting screenshot scan against 192.168.10.20/24
Starting verbose output. 
Project name: ornek-project 
Discovering live hosts. 
Discovered live host. Discovering open web ports. 
Host 192.168.10.20 port 80 open 
Host 192.168.10.20 port 443 open 
Host 192.168.10.20 port 8080 close 
Host 192.168.10.33 port 8443 open 
Taking screenshot 192.168.10.20:80 
Taking screenshot 192.168.10.20:443
Taking screenshot 192.168.10.33:8443 
Finished screenshot scan. Results saved in output/ornek-project/screen/ folder

**Comment by galkan** [comment]
ok
