### ISSUE TITLE
Verbose output 

### ISSUE THREAD

**Issue by BahtiyarB** [galkan/flashlight#3]
./fener.py -v  
tarama sırasında arka tarafta yapılan işlemleri ekrana ve log dosyasına yazar 
Örn: 
./fener.py -v -t 192.168.10.20/24 -s active -c config/fener.cfg -p project2 
Starting active scan against 192.168.10.20 
Starting nmap ping scan 
Discovering live host ip list 
Starting nmap port scan 
Starting nmap service detection 
Starting nmap OS detection 
Finished active scan. Results saved in  output/project2/nmap/ folder

**Comment by galkan** [comment]
ok
