### ISSUE TITLE
Gateway spesification in passive scan 

### ISSUE THREAD

**Issue by BahtiyarB** [galkan/flashlight#4]
pasif scan yaparken -m ile mitm yapılırsa arkada çalışan arpsooof için gateway paramtresini  okuyabilirsin. 

örnek komut: 
./flashlight -s passive -p 1 -m -k 30 -d 10.0.0.10 -i eth1   -k 300 
bu komut arkada arspoofu -d paramtresindeki gateway ile çalıştıracak 
komut: arpspoof -i eth1 10.0.0.10

**Comment by galkan** [comment]
done
